In [1]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "network_logs_1.csv"  

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "meruvakodandasuraj/cellular-network-handover-prediction-dataset",
    file_path
    )

df.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17872\1344225484.py:6: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

,Timestamp,DeviceID,deviceMake,deviceModel,Network provi.,NetworkType,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,11.05 km/h,18.109974,83.395252
1,2025-08-31 22:12:00.997,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,12.64 km/h,18.109945,83.395252
2,2025-08-31 22:11:59.990,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,13.00 km/h,18.109911,83.395249
3,2025-08-31 22:11:58.981,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,13.61 km/h,18.109869,83.395243
4,2025-08-31 22:11:57.972,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,14.40 km/h,18.109828,83.395233

## Data Exploration & Preprocessing

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10570 entries, 0 to 10569
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Timestamp        10570 non-null  str
 1   DeviceID         10570 non-null  str
 2   deviceMake       10570 non-null  str
 3   deviceModel      10570 non-null  str
 4   Network provi.   10570 non-null  str
 5    NetworkType     10570 non-null  str
 6   RSRP             10558 non-null  str
 7   RSRQ             10361 non-null  str
 8   SINR             10361 non-null  str
 9   PCI              10361 non-null  float64
 10  Downlink(Mbps)   10478 non-null  str
 11  Uplink(Mbps)     10478 non-null  str
 12  Velocity(km/h)   10301 non-null  str
 13  Latitude         10301 non-null  float64
 14  Longitude        10301 non-null  float64
dtypes: float64(3), str(12)
memory usage: 1.2 MB

In [3]:
df.dtypes

Timestamp              str
DeviceID               str
deviceMake             str
deviceModel            str
Network provi.         str
 NetworkType           str
RSRP                   str
RSRQ                   str
SINR                   str
PCI                float64
Downlink(Mbps)         str
Uplink(Mbps)           str
Velocity(km/h)         str
Latitude           float64
Longitude          float64
dtype: object

In [4]:
df.nunique()

Timestamp          10570
DeviceID               1
deviceMake             1
deviceModel            1
Network provi.         1
 NetworkType           5
RSRP                  62
RSRQ                  18
SINR                  39
PCI                  171
Downlink(Mbps)        44
Uplink(Mbps)          24
Velocity(km/h)      2404
Latitude            4778
Longitude           4682
dtype: int64

In [5]:
#Checking to see if there is a mix of data types in the columns

df["RSRP"].apply(type).value_counts()
df["RSRQ"].apply(type).value_counts()
df["SINR"].apply(type).value_counts()

SINR
<class 'str'>      10361
<class 'float'>      209
Name: count, dtype: int64

In [6]:
#Stripping units and converting to numeric float types

df['RSRP'] = df['RSRP'].str.replace(' dBm', '', regex=False)
df['RSRP'] = df['RSRP'].astype(float)

df['RSRQ'] = df['RSRQ'].str.replace(' dB', '', regex=False)
df['RSRQ'] = df['RSRQ'].astype(float)

df['SINR'] = df['SINR'].str.replace(' dB', '', regex=False)
df['SINR'] = df['SINR'].astype(float)

df['Velocity(km/h)'] = df['Velocity(km/h)'].str.replace(' km/h', '', regex=False)
df['Velocity(km/h)'] = df['Velocity(km/h)'].astype(float)

df["Downlink(Mbps)"] = df["Downlink(Mbps)"].str.replace(' Mbps', '', regex=False)
df["Downlink(Mbps)"] = df["Downlink(Mbps)"].astype(float)

df["Uplink(Mbps)"] = df["Uplink(Mbps)"].str.replace(' Mbps', '', regex=False)
df["Uplink(Mbps)"] = df["Uplink(Mbps)"].astype(float)

df.describe()

,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
count,10558.000000,10361.000000,1.036100e+04,10361.000000,10478.000000,10478.000000,10301.000000,10301.000000,10301.000000
mean,-99.715192,-12.653508,2.010481e+07,266.314931,19.447891,11.307597,38.842415,18.974445,82.924677
std,15.032208,2.661177,2.068204e+08,152.705732,14.031044,6.727758,36.540351,1.401074,0.684163
min,-129.000000,-20.000000,-1.200000e+01,2.000000,0.000000,0.000000,0.000000,17.721773,81.628921
25%,-111.000000,-14.000000,-3.000000e+00,170.000000,12.000000,4.000000,0.170000,18.052369,82.099433
50%,-100.000000,-12.000000,1.000000e+00,246.000000,15.000000,13.000000,31.540000,18.075481,83.315273
75%,-93.000000,-11.000000,6.000000e+00,403.000000,29.000000,16.000000,72.320000,21.113088,83.340455
max,-24.000000,-3.000000,2.147484e+09,502.000000,104.000000,38.000000,128.590000,21.271707,83.459252

In [7]:
#Identifying columns with missing values and their counts

df.isna().sum().sort_values(ascending=False)

Velocity(km/h)     269
Longitude          269
Latitude           269
RSRQ               209
SINR               209
PCI                209
Downlink(Mbps)      92
Uplink(Mbps)        92
RSRP                12
 NetworkType         0
Network provi.       0
Timestamp            0
DeviceID             0
deviceModel          0
deviceMake           0
dtype: int64

In [8]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df

,Timestamp,DeviceID,deviceMake,deviceModel,Network provi.,NetworkType,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252
1,2025-08-31 22:12:00.997,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252
2,2025-08-31 22:11:59.990,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249
3,2025-08-31 22:11:58.981,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243
4,2025-08-31 22:11:57.972,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10565,2025-08-28 14:15:42.151,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN
10566,2025-08-28 14:15:42.094,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN
10567,2025-08-28 14:15:42.038,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN
10568,2025-08-28 14:15:41.984,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN
10569,2025-08-28 14:15:41.926,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN

In [9]:
df.dtypes

Timestamp          datetime64[us]
DeviceID                      str
deviceMake                    str
deviceModel                   str
Network provi.                str
 NetworkType                  str
RSRP                      float64
RSRQ                      float64
SINR                      float64
PCI                       float64
Downlink(Mbps)            float64
Uplink(Mbps)              float64
Velocity(km/h)            float64
Latitude                  float64
Longitude                 float64
dtype: object

In [10]:
#Handling missing values in these columns by dropping them because handovers cannot be predicted without location and cell information.

df.dropna(subset=['Latitude', 'Longitude', 'PCI'], inplace=True)
df

,Timestamp,DeviceID,deviceMake,deviceModel,Network provi.,NetworkType,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252
1,2025-08-31 22:12:00.997,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252
2,2025-08-31 22:11:59.990,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249
3,2025-08-31 22:11:58.981,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243
4,2025-08-31 22:11:57.972,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10380,2025-08-28 14:36:13.024,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,1.23,21.130391,81.766043
10381,2025-08-28 14:36:12.013,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.09,21.130386,81.766042
10382,2025-08-28 14:36:11.004,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.15,21.130386,81.766042
10383,2025-08-28 14:36:09.988,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.32,21.130386,81.766041
10384,2025-08-28 14:36:08.973,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.35,21.130385,81.766041

In [11]:
df.isna().sum().sort_values(ascending=False)

Downlink(Mbps)     1
Uplink(Mbps)       1
Timestamp          0
deviceModel        0
Network provi.     0
DeviceID           0
deviceMake         0
RSRP               0
 NetworkType       0
SINR               0
RSRQ               0
PCI                0
Velocity(km/h)     0
Latitude           0
Longitude          0
dtype: int64

In [12]:
df.columns = df.columns.str.strip()
df

,Timestamp,DeviceID,deviceMake,deviceModel,Network provi.,NetworkType,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252
1,2025-08-31 22:12:00.997,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252
2,2025-08-31 22:11:59.990,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249
3,2025-08-31 22:11:58.981,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243
4,2025-08-31 22:11:57.972,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10380,2025-08-28 14:36:13.024,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,1.23,21.130391,81.766043
10381,2025-08-28 14:36:12.013,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.09,21.130386,81.766042
10382,2025-08-28 14:36:11.004,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.15,21.130386,81.766042
10383,2025-08-28 14:36:09.988,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.32,21.130386,81.766041
10384,2025-08-28 14:36:08.973,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.35,21.130385,81.766041

In [13]:
#Dropping columns that are not relevant for handover prediction and have a high number of unique values which may not be useful for modeling.

df.drop(columns=['DeviceID', 'deviceModel', 'deviceMake', "Network provi.", "NetworkType"], inplace=True, errors='ignore')

df

,Timestamp,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252
1,2025-08-31 22:12:00.997,-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252
2,2025-08-31 22:11:59.990,-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249
3,2025-08-31 22:11:58.981,-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243
4,2025-08-31 22:11:57.972,-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233
...,...,...,...,...,...,...,...,...,...,...
10380,2025-08-28 14:36:13.024,-129.0,-20.0,-7.0,464.0,35.0,4.0,1.23,21.130391,81.766043
10381,2025-08-28 14:36:12.013,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.09,21.130386,81.766042
10382,2025-08-28 14:36:11.004,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.15,21.130386,81.766042
10383,2025-08-28 14:36:09.988,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.32,21.130386,81.766041
10384,2025-08-28 14:36:08.973,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.35,21.130385,81.766041

In [14]:
df['Downlink(Mbps)'] = df['Downlink(Mbps)'].fillna(df['Downlink(Mbps)'].median())
df['Uplink(Mbps)'] = df['Uplink(Mbps)'].fillna(df['Uplink(Mbps)'].median())
df.isna().sum().sort_values(ascending=False)

Timestamp         0
RSRP              0
RSRQ              0
SINR              0
PCI               0
Downlink(Mbps)    0
Uplink(Mbps)      0
Velocity(km/h)    0
Latitude          0
Longitude         0
dtype: int64

In [15]:
#Validate ranges

df.loc[(df['RSRP'] > -44) | (df['RSRP'] < -140), 'RSRP'] = np.nan
df.loc[(df['RSRQ'] > -3) | (df['RSRQ'] < -20), 'RSRQ'] = np.nan
df.isna().sum().sort_values(ascending=False)

Timestamp         0
RSRP              0
RSRQ              0
SINR              0
PCI               0
Downlink(Mbps)    0
Uplink(Mbps)      0
Velocity(km/h)    0
Latitude          0
Longitude         0
dtype: int64

In [16]:
df['SINR'].min(), df['SINR'].max()

(np.float64(-12.0), np.float64(2147483647.0))

In [17]:
df.loc[df['SINR'] == 2147483647, 'SINR'] = np.nan

In [18]:
df['SINR'] =df['SINR'].fillna(df['SINR'].median())

In [19]:
df.describe()

,Timestamp,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
count,10251,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000
mean,2025-08-30 02:05:45.647030,-100.375280,-12.666081,1.574481,266.573310,19.478490,11.466101,38.907831,18.967897,82.928615
min,2025-08-28 14:36:08.973000,-129.000000,-20.000000,-12.000000,2.000000,0.000000,0.000000,0.000000,17.721773,81.628921
25%,2025-08-28 21:42:19.912500,-110.000000,-14.000000,-3.000000,170.000000,12.000000,4.000000,0.160000,18.052369,82.100663
50%,2025-08-29 06:40:13.345000,-100.000000,-12.000000,1.000000,246.000000,15.000000,13.000000,31.790000,18.074151,83.315623
75%,2025-08-31 21:59:06.944000,-93.000000,-11.000000,6.000000,406.000000,28.000000,16.000000,72.360000,21.113088,83.340625
max,2025-08-31 22:12:02.008000,-60.000000,-3.000000,28.000000,502.000000,104.000000,38.000000,128.590000,21.271707,83.459252
std,NaN,13.205192,2.669174,5.516042,153.155392,14.042806,6.703847,36.600946,1.397687,0.682100

In [20]:
df.isna().sum().sort_values(ascending=False)

Timestamp         0
RSRP              0
RSRQ              0
SINR              0
PCI               0
Downlink(Mbps)    0
Uplink(Mbps)      0
Velocity(km/h)    0
Latitude          0
Longitude         0
dtype: int64

In [21]:
df = df.sort_values(by='Timestamp').reset_index(drop=True)


df['hour'] = df['Timestamp'].dt.hour
df['minute'] = df['Timestamp'].dt.minute
df['second'] = df['Timestamp'].dt.second

In [22]:
#Creating a target variable 'Handover' which indicates whether a handover occurred (1) or not (0) based on changes in the PCI value between consecutive records.
df['Handover'] = (df['PCI'] != df['PCI'].shift(1)).astype(int)

df.loc[0, 'Handover'] = 0 #First record cannot be a handover since there is no previous record to compare with, so we set it to 0.

In [23]:
#Checking the distribution of the target variable to understand class imbalance

df['Handover'].value_counts()
df['Handover'].value_counts(normalize=True)

Handover
0    0.969076
1    0.030924
Name: proportion, dtype: float64

## Modeling

In [24]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

In [25]:
#Splitting the data in train and test sets for modeling, stratifying by the target variable to maintain class distribution in both sets.

X= df.drop(columns=['Timestamp', 'Handover'])
y = df['Handover']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [26]:
#Scaling after splitting to avoid data leakage from the test set into the training process, ensuring that the model is evaluated on unseen data.
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
#Applying SMOTE to the training data to address class imbalance by generating synthetic samples for the minority class (handovers).
smote = SMOTE(random_state=42)


X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

In [28]:
#Training the model using logistic regression with class weights to handle imbalance, and evaluating its performance on the test set.

model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train_scaled, y_train)

y_pred1 = model.predict(X_test_scaled)

In [29]:
#Training the second model using logistic regression on the SMOTE-resampled training data.

model2 = LogisticRegression(max_iter=1000)
model2.fit(X_train_smote, y_train_smote)

y_pred2 = model2.predict(X_test_scaled)

In [30]:
#Comparing the performance of both models using classification reports which include precision, recall, f1-score, and support for each class.

print("Model 1: Class Weight")
print(classification_report(y_test, y_pred1))

print("Model 2: SMOTE")
print(classification_report(y_test, y_pred2))

Model 1: Class Weight
              precision    recall  f1-score   support

           0       0.99      0.76      0.86      1988
           1       0.08      0.68      0.15        63

    accuracy                           0.76      2051
   macro avg       0.53      0.72      0.50      2051
weighted avg       0.96      0.76      0.84      2051

Model 2: SMOTE
              precision    recall  f1-score   support

           0       0.99      0.75      0.85      1988
           1       0.08      0.68      0.14        63

    accuracy                           0.75      2051
   macro avg       0.53      0.72      0.50      2051
weighted avg       0.96      0.75      0.83      2051

In [31]:
#Comparing the confusion matrices of both models to visualize the true positives, true negatives, false positives, and false negatives for each model.

print(confusion_matrix(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred2))

[[1508  480]
 [  20   43]]
[[1496  492]
 [  20   43]]

In [32]:
#Using Random Forest Classifier to see if it can improve performance compared to logistic regression.

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(class_weight='balanced', max_depth=1000, n_estimators=100)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

In [33]:
print(classification_report(y_test, y_pred_rf))

print(confusion_matrix(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1988
           1       0.18      0.05      0.07        63

    accuracy                           0.96      2051
   macro avg       0.57      0.52      0.53      2051
weighted avg       0.95      0.96      0.95      2051

[[1974   14]
 [  60    3]]

In [34]:
#Applying threshold tuning to optimize the decision threshold for classifying handovers, which may improve recall for the minority class at the cost of precision.

model_new = LogisticRegression(class_weight='balanced', max_iter=1000)
model_new.fit(X_train, y_train)

y_proba = model_new.predict_proba(X_test)[:, 1]

# try a threshold
threshold = 0.5
y_pred_new = (y_proba >= threshold).astype(int)

print(confusion_matrix(y_test, y_pred_new))
print(classification_report(y_test, y_pred_new))

[[1501  487]
 [  19   44]]
              precision    recall  f1-score   support

           0       0.99      0.76      0.86      1988
           1       0.08      0.70      0.15        63

    accuracy                           0.75      2051
   macro avg       0.54      0.73      0.50      2051
weighted avg       0.96      0.75      0.83      2051

## Feature Engineering

In [35]:
#Adding new features such as signal strength differences, and other features to potentially improve model performance by providing more information about the conditions leading to handovers.  

df['RSRP_diff'] = df['RSRP'] - df['RSRP'].shift(1)
df['RSRQ_diff'] = df['RSRQ'] - df['RSRQ'].shift(1)
df['SINR_diff'] = df['SINR'] - df['SINR'].shift(1)
df["velocity_diff"] = df["Velocity(km/h)"] - df["Velocity(km/h)"].shift(1)
df['RSRP_rolling_mean'] = df['RSRP'].rolling(window=5).mean()

In [36]:
# Dropping minutes and seconds column to remove noise

df.drop(columns=['minute', 'second'], inplace=True, errors='ignore')

In [37]:
df

,Timestamp,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude,hour,Handover,RSRP_diff,RSRQ_diff,SINR_diff,velocity_diff,RSRP_rolling_mean
0,2025-08-28 14:36:08.973,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.35,21.130385,81.766041,14,0,NaN,NaN,NaN,NaN,NaN
1,2025-08-28 14:36:09.988,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.32,21.130386,81.766041,14,0,0.0,0.0,0.0,-0.03,NaN
2,2025-08-28 14:36:11.004,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.15,21.130386,81.766042,14,0,0.0,0.0,0.0,-0.17,NaN
3,2025-08-28 14:36:12.013,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.09,21.130386,81.766042,14,0,0.0,0.0,0.0,-0.06,NaN
4,2025-08-28 14:36:13.024,-129.0,-20.0,-7.0,464.0,35.0,4.0,1.23,21.130391,81.766043,14,0,0.0,0.0,0.0,1.14,-129.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10246,2025-08-31 22:11:57.972,-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233,22,0,0.0,0.0,0.0,5.26,-99.0
10247,2025-08-31 22:11:58.981,-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243,22,0,0.0,0.0,0.0,-0.79,-99.0
10248,2025-08-31 22:11:59.990,-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249,22,0,0.0,0.0,0.0,-0.61,-99.0
10249,2025-08-31 22:12:00.997,-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252,22,0,0.0,0.0,0.0,-0.36,-99.0
10250,2025-08-31 22:12:02.008,-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252,22,0,0.0,0.0,0.0,-1.59,-99.0

In [38]:
df.isna().sum().sort_values(ascending=False)

RSRP_rolling_mean    4
velocity_diff        1
SINR_diff            1
RSRP_diff            1
RSRQ_diff            1
Timestamp            0
RSRP                 0
SINR                 0
RSRQ                 0
Latitude             0
Velocity(km/h)       0
Uplink(Mbps)         0
Downlink(Mbps)       0
PCI                  0
Handover             0
Longitude            0
hour                 0
dtype: int64

In [39]:
cols = ['RSRP_diff', 'RSRQ_diff', 'SINR_diff',
        'velocity_diff', 'RSRP_rolling_mean']

df[cols] = df[cols].fillna(0)

In [40]:
df.describe()

,Timestamp,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude,hour,Handover,RSRP_diff,RSRQ_diff,SINR_diff,velocity_diff,RSRP_rolling_mean
count,10251,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000,10251.000000
mean,2025-08-30 02:05:45.647030,-100.375280,-12.666081,1.574481,266.573310,19.478490,11.466101,38.907831,18.967897,82.928615,14.971125,0.030924,0.002927,0.000780,0.000683,0.001044,-100.330797
min,2025-08-28 14:36:08.973000,-129.000000,-20.000000,-12.000000,2.000000,0.000000,0.000000,0.000000,17.721773,81.628921,1.000000,0.000000,-31.000000,-10.000000,-22.000000,-113.220000,-129.000000
25%,2025-08-28 21:42:19.912500,-110.000000,-14.000000,-3.000000,170.000000,12.000000,4.000000,0.160000,18.052369,82.100663,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-110.000000
50%,2025-08-29 06:40:13.345000,-100.000000,-12.000000,1.000000,246.000000,15.000000,13.000000,31.790000,18.074151,83.315623,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000
75%,2025-08-31 21:59:06.944000,-93.000000,-11.000000,6.000000,406.000000,28.000000,16.000000,72.360000,21.113088,83.340625,21.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-93.000000
max,2025-08-31 22:12:02.008000,-60.000000,-3.000000,28.000000,502.000000,104.000000,38.000000,128.590000,21.271707,83.459252,22.000000,1.000000,29.000000,12.000000,27.000000,127.610000,0.000000
std,NaN,13.205192,2.669174,5.516042,153.155392,14.042806,6.703847,36.600946,1.397687,0.682100,7.566379,0.173120,2.052433,0.839628,1.226894,11.126499,13.237317

In [41]:
#Retraining the model with the new features to see if there is an improvement in performance.

X_fe= df.drop(columns=['Timestamp', 'Handover'])
y_fe = df['Handover']

X_train_fe, X_test_fe, y_train_fe, y_test_fe = train_test_split(X_fe, y_fe, test_size=0.2, random_state=42, stratify=y_fe)


#Scaling the new features after splitting to avoid data leakage and ensure that the model is evaluated on unseen data.
scaler = StandardScaler()
X_train_fe_scaled = scaler.fit_transform(X_train_fe)
X_test_fe_scaled = scaler.transform(X_test_fe)

In [42]:
#Applying SMOTE again with the new features to see if it can further improve performance.

X_train_fe_smote, y_train_fe_smote = smote.fit_resample(X_train_fe_scaled, y_train_fe)

fe_model_smote = LogisticRegression(max_iter=1000)
fe_model_smote.fit(X_train_fe_smote, y_train_fe_smote)


y_pred_fe_smote = fe_model_smote.predict(X_test_fe_scaled)

In [43]:
fe_model = LogisticRegression(class_weight='balanced', max_iter=1000)
fe_model.fit(X_train_fe_scaled, y_train_fe)
y_pred_fe = fe_model.predict(X_test_fe_scaled)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix
print("Model with New Features and SMOTE:")
print(classification_report(y_test_fe, y_pred_fe_smote))
print(confusion_matrix(y_test_fe, y_pred_fe_smote))

print("Model with New Features and Class Weight:")
print(classification_report(y_test_fe, y_pred_fe))
print(confusion_matrix(y_test_fe, y_pred_fe))

Model with New Features and SMOTE:
              precision    recall  f1-score   support

           0       0.98      0.79      0.88      1988
           1       0.08      0.60      0.15        63

    accuracy                           0.79      2051
   macro avg       0.53      0.70      0.51      2051
weighted avg       0.96      0.79      0.86      2051

[[1574  414]
 [  25   38]]
Model with New Features and Class Weight:
              precision    recall  f1-score   support

           0       0.98      0.79      0.88      1988
           1       0.08      0.60      0.15        63

    accuracy                           0.78      2051
   macro avg       0.53      0.70      0.51      2051
weighted avg       0.96      0.78      0.85      2051

[[1567  421]
 [  25   38]]

In [45]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

param_dist = {
    "n_estimators": [200, 300, 400, 500],
    "max_depth": [10, 15, 20, None],
    "min_samples_leaf": [1, 2, 5, 10],
    "min_samples_split": [2, 5, 10],
    "max_features": ["sqrt", "log2"]
}

rf = RandomForestClassifier(class_weight="balanced", random_state=42)

random_search = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=20,   # key change
    scoring="f1",
    cv=3,        # reduce folds
    n_jobs=-1,
    random_state=42
)

random_search.fit(X_train_fe, y_train_fe)

best_model = random_search.best_estimator_

In [46]:
y_pred_fe = best_model.predict(X_test_fe)

print(classification_report(y_test_fe, y_pred_fe))
print(confusion_matrix(y_test_fe, y_pred_fe))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1988
           1       0.59      0.84      0.69        63

    accuracy                           0.98      2051
   macro avg       0.79      0.91      0.84      2051
weighted avg       0.98      0.98      0.98      2051

[[1951   37]
 [  10   53]]

In [47]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

y_prob_fe = best_model.predict_proba(X_test_fe)[:, 1]

for t in np.arange(0.2, 0.6, 0.05):
    y_pred_fe = (y_prob_fe >= t).astype(int)
    print(
        t,
        recall_score(y_test_fe, y_pred_fe),
        precision_score(y_test_fe, y_pred_fe),
        f1_score(y_test_fe, y_pred_fe)
    )

0.2 1.0 0.38414634146341464 0.5550660792951542
0.25 0.9841269841269841 0.40789473684210525 0.5767441860465117
0.3 0.9682539682539683 0.43884892086330934 0.6039603960396039
0.35 0.9365079365079365 0.47580645161290325 0.6310160427807486
0.39999999999999997 0.9206349206349206 0.5 0.6480446927374302
0.44999999999999996 0.873015873015873 0.5445544554455446 0.6707317073170732
0.49999999999999994 0.8412698412698413 0.5888888888888889 0.6928104575163399
0.5499999999999999 0.8095238095238095 0.6071428571428571 0.6938775510204082

In [48]:
#Using Random Forest 
fe_rf_model = RandomForestClassifier(class_weight='balanced', max_depth=15, random_state=42, n_estimators=300)
fe_rf_model.fit(X_train_fe, y_train_fe)
y_pred_fe_rf = fe_rf_model.predict(X_test_fe)
print(classification_report(y_test_fe, y_pred_fe_rf))
print(confusion_matrix(y_test_fe, y_pred_fe_rf))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1988
           1       0.78      0.62      0.69        63

    accuracy                           0.98      2051
   macro avg       0.88      0.81      0.84      2051
weighted avg       0.98      0.98      0.98      2051

[[1977   11]
 [  24   39]]

In [49]:
#Using feature importance from the random forest model to identify which features are most influential in predicting handovers, which can provide insights into the factors that contribute to handovers and guide further feature engineering efforts.
feature_importances = fe_rf_model.feature_importances_
feature_names = X_fe.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})
feature_importance_df.sort_values(by='Importance', ascending=False, inplace=True)
feature_importance_df

              Feature  Importance
10          RSRP_diff    0.258409
12          SINR_diff    0.216348
11          RSRQ_diff    0.173971
7            Latitude    0.068583
8           Longitude    0.066527
6      Velocity(km/h)    0.043539
2                SINR    0.029569
14  RSRP_rolling_mean    0.028967
0                RSRP    0.021414
13      velocity_diff    0.020422
9                hour    0.016898
3                 PCI    0.016030
1                RSRQ    0.015430
5        Uplink(Mbps)    0.013298
4      Downlink(Mbps)    0.010594

In [50]:
#Trying Decision Tree Classifier to see if it can capture non-linear relationships in the data and improve performance compared to logistic regression and random forest.
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(class_weight='balanced', max_depth=300)
dt_model.fit(X_train_fe, y_train_fe)
y_pred_dt = dt_model.predict(X_test_fe)
print(classification_report(y_test_fe, y_pred_dt))
print(confusion_matrix(y_test_fe, y_pred_dt))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1988
           1       0.63      0.60      0.62        63

    accuracy                           0.98      2051
   macro avg       0.81      0.80      0.80      2051
weighted avg       0.98      0.98      0.98      2051

[[1966   22]
 [  25   38]]

In [55]:
#Using XGBoost Classifier to see if it can further improve performance by leveraging gradient boosting techniques to capture complex patterns in the data.
from xgboost import XGBClassifier
xgb_model = XGBClassifier(class_weight='balanced', max_depth=15, random_state=42, n_estimators=300, scale_pos_weight=31.6)
xgb_model.fit(X_train_fe, y_train_fe)
y_pred_xgb = xgb_model.predict(X_test_fe)
print(classification_report(y_test_fe, y_pred_xgb))     
print(confusion_matrix(y_test_fe, y_pred_xgb))

c:\Users\LENOVO\Documents\My Project\network-handover-prediction\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:50:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "class_weight" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1988
           1       0.64      0.71      0.68        63

    accuracy                           0.98      2051
   macro avg       0.82      0.85      0.83      2051
weighted avg       0.98      0.98      0.98      2051

[[1963   25]
 [  18   45]]

In [58]:
fe_y_probs = xgb_model.predict_proba(X_test_fe)[:, 1]
thresholds = [0.2, 0.3, 0.4, 0.5]

for t in thresholds:
    fe_y_pred = (fe_y_probs >= t).astype(int)
    print(f"Threshold: {t}")
    print(classification_report(y_test_fe, fe_y_pred))
    print(confusion_matrix(y_test_fe, fe_y_pred))

Threshold: 0.2
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1988
           1       0.57      0.76      0.65        63

    accuracy                           0.98      2051
   macro avg       0.78      0.87      0.82      2051
weighted avg       0.98      0.98      0.98      2051

[[1952   36]
 [  15   48]]
Threshold: 0.3
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1988
           1       0.57      0.73      0.64        63

    accuracy                           0.98      2051
   macro avg       0.78      0.86      0.82      2051
weighted avg       0.98      0.98      0.98      2051

[[1954   34]
 [  17   46]]
Threshold: 0.4
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1988
           1       0.61      0.73      0.66        63

    accuracy                           0.98      2051
   macro avg       0.80      0.86      0.83      2051
weighted avg       0.98      0.98      0.98      2051

[[1958   30]
 [  17   46]]
Threshold: 0.5
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1988
           1       0.64      0.71      0.68        63

    accuracy                           0.98      2051
   macro avg       0.82      0.85      0.83      2051
weighted avg       0.98      0.98      0.98      2051

[[1963   25]
 [  18   45]]