In [58]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "network_logs_1.csv"  

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "meruvakodandasuraj/cellular-network-handover-prediction-dataset",
    file_path
    )

df.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_2184\1344225484.py:6: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

,Timestamp,DeviceID,deviceMake,deviceModel,Network provi.,NetworkType,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,11.05 km/h,18.109974,83.395252
1,2025-08-31 22:12:00.997,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,12.64 km/h,18.109945,83.395252
2,2025-08-31 22:11:59.990,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,13.00 km/h,18.109911,83.395249
3,2025-08-31 22:11:58.981,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,13.61 km/h,18.109869,83.395243
4,2025-08-31 22:11:57.972,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99 dBm,-12 dB,0 dB,371.0,29 Mbps,18 Mbps,14.40 km/h,18.109828,83.395233

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10570 entries, 0 to 10569
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Timestamp        10570 non-null  str
 1   DeviceID         10570 non-null  str
 2   deviceMake       10570 non-null  str
 3   deviceModel      10570 non-null  str
 4   Network provi.   10570 non-null  str
 5    NetworkType     10570 non-null  str
 6   RSRP             10558 non-null  str
 7   RSRQ             10361 non-null  str
 8   SINR             10361 non-null  str
 9   PCI              10361 non-null  float64
 10  Downlink(Mbps)   10478 non-null  str
 11  Uplink(Mbps)     10478 non-null  str
 12  Velocity(km/h)   10301 non-null  str
 13  Latitude         10301 non-null  float64
 14  Longitude        10301 non-null  float64
dtypes: float64(3), str(12)
memory usage: 1.2 MB

In [60]:
df.dtypes

Timestamp              str
DeviceID               str
deviceMake             str
deviceModel            str
Network provi.         str
 NetworkType           str
RSRP                   str
RSRQ                   str
SINR                   str
PCI                float64
Downlink(Mbps)         str
Uplink(Mbps)           str
Velocity(km/h)         str
Latitude           float64
Longitude          float64
dtype: object

In [61]:
df.nunique()

Timestamp          10570
DeviceID               1
deviceMake             1
deviceModel            1
Network provi.         1
 NetworkType           5
RSRP                  62
RSRQ                  18
SINR                  39
PCI                  171
Downlink(Mbps)        44
Uplink(Mbps)          24
Velocity(km/h)      2404
Latitude            4778
Longitude           4682
dtype: int64

In [62]:
#Checking to see if there is a mix of data types in the columns

df["RSRP"].apply(type).value_counts()
df["RSRQ"].apply(type).value_counts()
df["SINR"].apply(type).value_counts()

SINR
<class 'str'>      10361
<class 'float'>      209
Name: count, dtype: int64

In [63]:
#Stripping units and converting to numeric float types

df['RSRP'] = df['RSRP'].str.replace(' dBm', '', regex=False)
df['RSRP'] = df['RSRP'].astype(float)

df['RSRQ'] = df['RSRQ'].str.replace(' dB', '', regex=False)
df['RSRQ'] = df['RSRQ'].astype(float)

df['SINR'] = df['SINR'].str.replace(' dB', '', regex=False)
df['SINR'] = df['SINR'].astype(float)

df['Velocity(km/h)'] = df['Velocity(km/h)'].str.replace(' km/h', '', regex=False)
df['Velocity(km/h)'] = df['Velocity(km/h)'].astype(float)

df["Downlink(Mbps)"] = df["Downlink(Mbps)"].str.replace(' Mbps', '', regex=False)
df["Downlink(Mbps)"] = df["Downlink(Mbps)"].astype(float)

df["Uplink(Mbps)"] = df["Uplink(Mbps)"].str.replace(' Mbps', '', regex=False)
df["Uplink(Mbps)"] = df["Uplink(Mbps)"].astype(float)

df.describe()

,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
count,10558.000000,10361.000000,1.036100e+04,10361.000000,10478.000000,10478.000000,10301.000000,10301.000000,10301.000000
mean,-99.715192,-12.653508,2.010481e+07,266.314931,19.447891,11.307597,38.842415,18.974445,82.924677
std,15.032208,2.661177,2.068204e+08,152.705732,14.031044,6.727758,36.540351,1.401074,0.684163
min,-129.000000,-20.000000,-1.200000e+01,2.000000,0.000000,0.000000,0.000000,17.721773,81.628921
25%,-111.000000,-14.000000,-3.000000e+00,170.000000,12.000000,4.000000,0.170000,18.052369,82.099433
50%,-100.000000,-12.000000,1.000000e+00,246.000000,15.000000,13.000000,31.540000,18.075481,83.315273
75%,-93.000000,-11.000000,6.000000e+00,403.000000,29.000000,16.000000,72.320000,21.113088,83.340455
max,-24.000000,-3.000000,2.147484e+09,502.000000,104.000000,38.000000,128.590000,21.271707,83.459252

In [64]:
#Identifying columns with missing values and their counts

df.isna().sum().sort_values(ascending=False)

Velocity(km/h)     269
Longitude          269
Latitude           269
RSRQ               209
SINR               209
PCI                209
Downlink(Mbps)      92
Uplink(Mbps)        92
RSRP                12
 NetworkType         0
Network provi.       0
Timestamp            0
DeviceID             0
deviceModel          0
deviceMake           0
dtype: int64

In [65]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df

,Timestamp,DeviceID,deviceMake,deviceModel,Network provi.,NetworkType,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252
1,2025-08-31 22:12:00.997,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252
2,2025-08-31 22:11:59.990,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249
3,2025-08-31 22:11:58.981,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243
4,2025-08-31 22:11:57.972,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10565,2025-08-28 14:15:42.151,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN
10566,2025-08-28 14:15:42.094,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN
10567,2025-08-28 14:15:42.038,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN
10568,2025-08-28 14:15:41.984,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN
10569,2025-08-28 14:15:41.926,65bb12ad684ceba4,samsung,SM-S901E,airtel,WCDMA (3G),-24.0,NaN,NaN,NaN,8.0,3.0,NaN,NaN,NaN

In [66]:
df.dtypes

Timestamp          datetime64[us]
DeviceID                      str
deviceMake                    str
deviceModel                   str
Network provi.                str
 NetworkType                  str
RSRP                      float64
RSRQ                      float64
SINR                      float64
PCI                       float64
Downlink(Mbps)            float64
Uplink(Mbps)              float64
Velocity(km/h)            float64
Latitude                  float64
Longitude                 float64
dtype: object

In [67]:
#Handling missing values in these columns by dropping them because handovers cannot be predicted without location and cell information.

df.dropna(subset=['Latitude', 'Longitude', 'PCI'], inplace=True)
df

,Timestamp,DeviceID,deviceMake,deviceModel,Network provi.,NetworkType,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252
1,2025-08-31 22:12:00.997,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252
2,2025-08-31 22:11:59.990,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249
3,2025-08-31 22:11:58.981,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243
4,2025-08-31 22:11:57.972,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10380,2025-08-28 14:36:13.024,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,1.23,21.130391,81.766043
10381,2025-08-28 14:36:12.013,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.09,21.130386,81.766042
10382,2025-08-28 14:36:11.004,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.15,21.130386,81.766042
10383,2025-08-28 14:36:09.988,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.32,21.130386,81.766041
10384,2025-08-28 14:36:08.973,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.35,21.130385,81.766041

In [68]:
df.isna().sum().sort_values(ascending=False)

Downlink(Mbps)     1
Uplink(Mbps)       1
Timestamp          0
deviceModel        0
Network provi.     0
DeviceID           0
deviceMake         0
RSRP               0
 NetworkType       0
SINR               0
RSRQ               0
PCI                0
Velocity(km/h)     0
Latitude           0
Longitude          0
dtype: int64

In [71]:
df.columns = df.columns.str.strip()
df

,Timestamp,DeviceID,deviceMake,deviceModel,Network provi.,NetworkType,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252
1,2025-08-31 22:12:00.997,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252
2,2025-08-31 22:11:59.990,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249
3,2025-08-31 22:11:58.981,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243
4,2025-08-31 22:11:57.972,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10380,2025-08-28 14:36:13.024,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,1.23,21.130391,81.766043
10381,2025-08-28 14:36:12.013,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.09,21.130386,81.766042
10382,2025-08-28 14:36:11.004,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.15,21.130386,81.766042
10383,2025-08-28 14:36:09.988,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.32,21.130386,81.766041
10384,2025-08-28 14:36:08.973,65bb12ad684ceba4,samsung,SM-S901E,airtel,LTE (4G),-129.0,-20.0,-7.0,464.0,35.0,4.0,0.35,21.130385,81.766041

In [ ]:

df.drop(columns=['DeviceID', 'deviceModel', 'deviceMake', "Network provi.", "NetworkType"], inplace=True, errors='ignore')

df

,Timestamp,RSRP,RSRQ,SINR,PCI,Downlink(Mbps),Uplink(Mbps),Velocity(km/h),Latitude,Longitude
0,2025-08-31 22:12:02.008,-99.0,-12.0,0.0,371.0,29.0,18.0,11.05,18.109974,83.395252
1,2025-08-31 22:12:00.997,-99.0,-12.0,0.0,371.0,29.0,18.0,12.64,18.109945,83.395252
2,2025-08-31 22:11:59.990,-99.0,-12.0,0.0,371.0,29.0,18.0,13.00,18.109911,83.395249
3,2025-08-31 22:11:58.981,-99.0,-12.0,0.0,371.0,29.0,18.0,13.61,18.109869,83.395243
4,2025-08-31 22:11:57.972,-99.0,-12.0,0.0,371.0,29.0,18.0,14.40,18.109828,83.395233
...,...,...,...,...,...,...,...,...,...,...
10380,2025-08-28 14:36:13.024,-129.0,-20.0,-7.0,464.0,35.0,4.0,1.23,21.130391,81.766043
10381,2025-08-28 14:36:12.013,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.09,21.130386,81.766042
10382,2025-08-28 14:36:11.004,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.15,21.130386,81.766042
10383,2025-08-28 14:36:09.988,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.32,21.130386,81.766041
10384,2025-08-28 14:36:08.973,-129.0,-20.0,-7.0,464.0,35.0,4.0,0.35,21.130385,81.766041